name: wg_mesh_test
services:
  node1:
    build: .
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ../src:/app/src:ro
      - ./runtime_conf/config1.json:/app/config.json
    networks:
      main:
        ipv4_address: 172.20.123.1

  node2:
    build: .
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ../src:/app/src:ro
      - ./runtime_conf/config2.json:/app/config.json
    networks:
      main:
        ipv4_address: 172.20.123.2

  node3:
    build: .
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ../src:/app/src:ro
      - ./runtime_conf/config3.json:/app/config.json
    networks:
      main:
        ipv4_address: 172.20.123.3

  node4:
    build: .
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ../src:/app/src:ro
      - ./runtime_conf/config4.json:/app/config.json
    networks:
      main:
        ipv4_address: 172.20.123.4

  node5:
    build: .
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ../src:/app/src:ro
      - ./runtime_conf/config5.json:/app/config.json
    command: sh -c 'echo "Node 5 sleeping for 5s to let meshes form..." && sleep 5 && exec python -m src.mesh --config /app/config.json -vv'
    networks:
      main:
        ipv4_address: 172.20.123.5

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.123.0/24
          gateway: 172.20.123.234
